name: Quality pipeline

on:
  pull_request:
    branches:
      - main
      - release-*

jobs:
  quality_pipeline_lint_and_typecheck:
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type Check
        run: npm run test-types

  quality_pipeline_nodejs:
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test:nodejs

      - name: Report coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  quality_pipeline_chromium:
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: '24.15.0'

      - name: Install
        run: npm ci && npx playwright install --with-deps chromium

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test:chromium

      - name: Report coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  quality_pipeline_firefox:
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: '24.15.0'

      - name: Install
        run: npm ci && npx playwright install --with-deps firefox

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test:firefox

  quality_pipeline_webkit:
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: '24.15.0'

      - name: Install
        run: npm ci && npx playwright install --with-deps webkit

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test:webkit
