name: Release (Git tag)

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version bump kind"
        required: true
        type: choice
        options: ["patch", "minor", "major"]

jobs:
  release:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.OO_CI_AT }}

      - name: Setup NodeJS 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Bump & Tag version
        run: |
          git config user.name "automation"
          npm version ${{ github.event.inputs.version }}
