name: Deploy 'object-observer' to CDN

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true

jobs:
  release-deploy:
    runs-on: ubuntu-18.04

    steps:
      - name: Setup NodeJS 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      # Get release version
      - name: Get release version
        run: echo "RELEASE_VERSION=${{ github.event.client_payload.version }}" >> $GITHUB_ENV

      - name: Install
        run: npm install -E object-observer@${{ env.RELEASE_VERSION }}

      # Deploy
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET }}
        run: aws s3 sync ./node_modules/object-observer/dist/cdn s3://${{ secrets.AWS_LIBS_BUCKET }}/object-observer/${{ env.RELEASE_VERSION }} --delete --cache-control public,max-age=172800,immutable
